export const ADD_PRODUCT_TO_CART = 'ADD_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_FROM_CART';
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const GET_PRODUCTS_PENDING = 'FETCH_PRODUCTS_PENDING';
export const GET_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';
