export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';
export const FILTER_PRODUCTS_BY_NAME = 'FILTER_PRODUCTS_BY_NAME';
export const FILTER_PRODUCTS_BY_CATEGORY = 'FILTER_PRODUCTS_BY_CATEGORY';
export const NEXT_PRODUCT_PAGE = 'NEXT_PRODUCT_PAGE';
export const PREV_PRODUCT_PAGE = 'PREV_PRODUCT_PAGE';
export const JUMP_PRODUCT_PAGE = 'JUMP_PRODUCT_PAGE';


