version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.2
    - 12.6.3
    - 12.7.0
    - 12.7.3
    - 12.8.0
    - 12.8.1
    - 13.0.0
    - 13.0.1
    - 13.1.1
    - 13.1.2
    - 13.1.5
  - dependency-name: "@storybook/addon-a11y"
    versions:
    - 6.1.15
    - 6.1.16
    - 6.1.17
    - 6.1.18
    - 6.1.20
    - 6.1.21
    - 6.2.7
    - 6.2.8
  - dependency-name: "@storybook/addon-viewport"
    versions:
    - 6.1.15
    - 6.1.16
    - 6.1.17
    - 6.1.18
    - 6.1.19
    - 6.1.20
    - 6.1.21
    - 6.2.1
    - 6.2.2
    - 6.2.4
    - 6.2.5
    - 6.2.7
    - 6.2.8
  - dependency-name: "@storybook/addon-links"
    versions:
    - 6.1.15
    - 6.1.16
    - 6.1.17
    - 6.1.18
    - 6.1.20
    - 6.1.21
    - 6.2.3
    - 6.2.7
    - 6.2.8
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.15
    - 6.1.17
    - 6.1.21
  - dependency-name: "@storybook/preset-create-react-app"
    versions:
    - 3.0.1
    - 3.1.6
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
