export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CHECKOUT_CART = 'CHECKOUT_CART';
export const EMPTY_CART = 'EMPTY_CART';
export const INCREMENT_CART_ITEM_COUNT = 'INCREMENT_CART_ITEM_COUNT';
export const DECREMENT_CART_ITEM_COUNT = 'DECREMENT_CART_ITEM_COUNT';
export const ADD_TO_CART = 'ADD_TO_CART';
export const GET_USER_CART = 'GET_USER_CART';
