export const CONFIRM_ORDER = 'CONFIRM_ORDER';
export const CLEAR_ORDER = 'CLEAR_ORDER';
export const CREATE_ORDER = 'CREATE_ORDER';
export const ORDER_RECEIVED = 'ORDER_RECEIVED';
export const ORDER_COMPLETE = 'ORDER_COMPLETE';
export const FETCH_ORDERS = 'FETCH_ORDERS';
